[project]
name = "hibou_vision"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorlog>=6.10.1",
    "datasets>=4.8.5",
    "dotenv>=0.9.9",
    "imagecodecs>=2026.3.6",
    "opencv-python>=4.13.0.92",
    "pillow>=12.2.0",
    "pyyaml>=6.0.3",
    "torch>=2.11.0",
    "ultralytics>=8.4.43",
    "wandb>=0.26.1",
]
