model:
  yolo_version: "26"
  model_size: "nano"

labels:
  load_other: false

dataset:
  hf_name: "Hibou-Foundation/computer-vision"
  hf_revision: "main"
  image_transform: "RGB"

train:
  batch: 16
  epochs: 100
  optimizer: AdamW
  lr0: 0.0001

augmentation:
  degrees: 5
  perspective: 0.0002
  scale: 0.05
  mosaic: 0.3
  close_mosaic: 50
  cutmix: 0.3
  flip_lr: 0.3
  shear: 5

validation:
  visualize: true
  save: true
  split: test

reproducibility:
  seed: 42

logging:
  use_wandb: false