model:
  yolo_version: "26"
  model_size: "nano"

labels:
  load_other: false

dataset:
  image_transform: "RGB"
  split_ratio: [0.8, 0.1, 0.1] # Train, val, test
  providers:
    hf:
      - name: "Hibou-Foundation/computer-vision"
        revision: "main"
    aws_s3:
      - bucket: "axair-datasets"
        region: "eu-central-1"
        folder: "RGB/UAV/ODIN/"
#    local:
#      - path: "datasets/drone_test/"


#https://docs.ultralytics.com/modes/train/
train:
  batch: 16
  epochs: 1
  optimizer: AdamW
  lr0: 0.0001

  # Data augmentation parameters
  # https://docs.ultralytics.com/guides/yolo-data-augmentation/
  degrees: 5
  perspective: 0.0002
  scale: 0.05
  mosaic: 0.3
  close_mosaic: 50
  cutmix: 0.3
  fliplr: 0.3
  shear: 5

#https://docs.ultralytics.com/modes/val/
validation:
  visualize: true
  save: true
  split: test

#https://docs.ultralytics.com/modes/benchmark/
benchmark:
  half: false
  int8: false
  batch: 1

reproducibility:
  seed: 42